// Code generated by "stringer -type=Sports"; DO NOT EDIT.

package sports

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Null-0]
	_ = x[Baseball-1]
	_ = x[Swimming-2]
	_ = x[Soccer-3]
	_ = x[Karate-4]
}

const _Sports_name = "NullBaseballSwimmingSoccerKarate"

var _Sports_index = [...]uint8{0, 4, 12, 20, 26, 32}

func (i Sports) String() string {
	if i < 0 || i >= Sports(len(_Sports_index)-1) {
		return "Sports(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Sports_name[_Sports_index[i]:_Sports_index[i+1]]
}
