// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/task.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Level int32

const (
	Level_LEVEL_UNKNOWN Level = 0
	Level_LOW           Level = 1
	Level_MID           Level = 2
	Level_HIGH          Level = 3
)

var Level_name = map[int32]string{
	0: "LEVEL_UNKNOWN",
	1: "LOW",
	2: "MID",
	3: "HIGH",
}

var Level_value = map[string]int32{
	"LEVEL_UNKNOWN": 0,
	"LOW":           1,
	"MID":           2,
	"HIGH":          3,
}

func (x Level) String() string {
	return proto.EnumName(Level_name, int32(x))
}

func (Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5de11d747d3f16e6, []int{0}
}

type Status int32

const (
	Status_STATUS_UNKNOWN Status = 0
	Status_TODO           Status = 1
	Status_IN_PROGRESS    Status = 2
	Status_DONE           Status = 3
)

var Status_name = map[int32]string{
	0: "STATUS_UNKNOWN",
	1: "TODO",
	2: "IN_PROGRESS",
	3: "DONE",
}

var Status_value = map[string]int32{
	"STATUS_UNKNOWN": 0,
	"TODO":           1,
	"IN_PROGRESS":    2,
	"DONE":           3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5de11d747d3f16e6, []int{1}
}

type Task struct {
	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Level       Level  `protobuf:"varint,3,opt,name=level,proto3,enum=proto.Level" json:"level,omitempty"`
	Status      Status `protobuf:"varint,4,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to MemoOptional:
	//	*Task_Memo
	MemoOptional         isTask_MemoOptional `protobuf_oneof:"memo_optional"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_5de11d747d3f16e6, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Task) GetLevel() Level {
	if m != nil {
		return m.Level
	}
	return Level_LEVEL_UNKNOWN
}

func (m *Task) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_STATUS_UNKNOWN
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type isTask_MemoOptional interface {
	isTask_MemoOptional()
}

type Task_Memo struct {
	Memo string `protobuf:"bytes,6,opt,name=memo,proto3,oneof"`
}

func (*Task_Memo) isTask_MemoOptional() {}

func (m *Task) GetMemoOptional() isTask_MemoOptional {
	if m != nil {
		return m.MemoOptional
	}
	return nil
}

func (m *Task) GetMemo() string {
	if x, ok := m.GetMemoOptional().(*Task_Memo); ok {
		return x.Memo
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Task) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Task_Memo)(nil),
	}
}

func init() {
	proto.RegisterEnum("proto.Level", Level_name, Level_value)
	proto.RegisterEnum("proto.Status", Status_name, Status_value)
	proto.RegisterType((*Task)(nil), "proto.Task")
}

func init() { proto.RegisterFile("proto/task.proto", fileDescriptor_5de11d747d3f16e6) }

var fileDescriptor_5de11d747d3f16e6 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x4f, 0x6b, 0xf2, 0x40,
	0x10, 0xc6, 0xdd, 0xfc, 0x7b, 0x7d, 0xc7, 0xaa, 0xdb, 0xc1, 0x43, 0x28, 0x3d, 0x04, 0xa1, 0x20,
	0x1e, 0x14, 0x5a, 0xe8, 0xdd, 0x62, 0x50, 0x69, 0x9a, 0x94, 0x4d, 0xac, 0x47, 0xd9, 0xd6, 0x20,
	0x8b, 0xd1, 0x0d, 0xee, 0xb6, 0x9f, 0xaf, 0x1f, 0xad, 0x64, 0xd7, 0x83, 0xa7, 0x99, 0x79, 0x9e,
	0xdf, 0xce, 0x3c, 0x0b, 0xb4, 0x3e, 0x4b, 0x2d, 0xa7, 0x9a, 0xab, 0xc3, 0xc4, 0xb4, 0xe8, 0x9b,
	0x72, 0x77, 0xbf, 0x97, 0x72, 0x5f, 0x95, 0x53, 0x5e, 0x8b, 0x29, 0x3f, 0x9d, 0xa4, 0xe6, 0x5a,
	0xc8, 0x93, 0xb2, 0xd0, 0xf0, 0x97, 0x80, 0x57, 0x70, 0x75, 0xc0, 0x1e, 0x38, 0x62, 0x17, 0x92,
	0x88, 0x8c, 0x5c, 0xe6, 0x88, 0x1d, 0x0e, 0xc0, 0xd7, 0x42, 0x57, 0x65, 0xe8, 0x44, 0x64, 0xf4,
	0x9f, 0xd9, 0x01, 0x87, 0xe0, 0x57, 0xe5, 0x4f, 0x59, 0x85, 0x6e, 0x44, 0x46, 0xbd, 0xc7, 0x1b,
	0xbb, 0x65, 0x92, 0x34, 0x1a, 0xb3, 0x16, 0x3e, 0x40, 0xa0, 0x34, 0xd7, 0xdf, 0x2a, 0xf4, 0x0c,
	0xd4, 0xbd, 0x40, 0xb9, 0x11, 0xd9, 0xc5, 0xc4, 0x08, 0x3a, 0xbb, 0x52, 0x7d, 0x9d, 0x45, 0xdd,
	0xe4, 0x09, 0x7d, 0x73, 0xe6, 0x5a, 0xc2, 0x01, 0x78, 0xc7, 0xf2, 0x28, 0xc3, 0xa0, 0xb1, 0x96,
	0x2d, 0x66, 0xa6, 0x97, 0x3e, 0x74, 0x9b, 0xba, 0x95, 0x06, 0xe2, 0xd5, 0xf8, 0x19, 0x7c, 0x73,
	0x1f, 0x6f, 0xa1, 0x9b, 0xc4, 0x1f, 0x71, 0xb2, 0x5d, 0xa7, 0xaf, 0x69, 0xb6, 0x49, 0x69, 0x0b,
	0xff, 0x81, 0x9b, 0x64, 0x1b, 0x4a, 0x9a, 0xe6, 0x6d, 0x35, 0xa7, 0x0e, 0xb6, 0xc1, 0x5b, 0xae,
	0x16, 0x4b, 0xea, 0x8e, 0x67, 0x10, 0xd8, 0x48, 0x88, 0xd0, 0xcb, 0x8b, 0x59, 0xb1, 0xce, 0xaf,
	0x5e, 0xb6, 0xc1, 0x2b, 0xb2, 0x79, 0x46, 0x09, 0xf6, 0xa1, 0xb3, 0x4a, 0xb7, 0xef, 0x2c, 0x5b,
	0xb0, 0x38, 0xcf, 0xed, 0x8a, 0x79, 0x96, 0xc6, 0xd4, 0xfd, 0x0c, 0xcc, 0xcf, 0x9e, 0xfe, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x96, 0xfe, 0x7e, 0xf0, 0x7d, 0x01, 0x00, 0x00,
}
