// Code generated by "stringer -type=DeviceType"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeviceTypeNull-0]
	_ = x[DeviceTypeIos-1]
	_ = x[DeviceTypeAndroid-2]
	_ = x[DeviceTypeWindows-3]
	_ = x[DeviceTypeLinux-4]
}

const _DeviceType_name = "DeviceTypeNullDeviceTypeIosDeviceTypeAndroidDeviceTypeWindowsDeviceTypeLinux"

var _DeviceType_index = [...]uint8{0, 14, 27, 44, 61, 76}

func (i DeviceType) String() string {
	if i < 0 || i >= DeviceType(len(_DeviceType_index)-1) {
		return "DeviceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceType_name[_DeviceType_index[i]:_DeviceType_index[i+1]]
}
