// Code generated by "stringer -type=Version"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VersionNull-0]
	_ = x[Version0000-1]
	_ = x[Version2017-2]
	_ = x[Version2018-3]
	_ = x[Version2019-4]
}

const _Version_name = "VersionNullVersion0000Version2017Version2018Version2019"

var _Version_index = [...]uint8{0, 11, 22, 33, 44, 55}

func (i Version) String() string {
	if i < 0 || i >= Version(len(_Version_index)-1) {
		return "Version(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Version_name[_Version_index[i]:_Version_index[i+1]]
}
