// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package entity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Country int32

const (
	Country_UNKNOWN Country = 0
	Country_US      Country = 1
	Country_JP      Country = 2
)

var Country_name = map[int32]string{
	0: "UNKNOWN",
	1: "US",
	2: "JP",
}

var Country_value = map[string]int32{
	"UNKNOWN": 0,
	"US":      1,
	"JP":      2,
}

func (x Country) String() string {
	return proto.EnumName(Country_name, int32(x))
}

func (Country) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

type User struct {
	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to NicknameOptional:
	//	*User_Nickname
	NicknameOptional isUser_NicknameOptional `protobuf_oneof:"nickname_optional"`
	// Types that are valid to be assigned to AgeOptional:
	//	*User_Age
	AgeOptional          isUser_AgeOptional `protobuf_oneof:"age_optional"`
	Birth                *Birth             `protobuf:"bytes,5,opt,name=birth,proto3" json:"birth,omitempty"`
	Addresss             *Address           `protobuf:"bytes,6,opt,name=addresss,proto3" json:"addresss,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isUser_NicknameOptional interface {
	isUser_NicknameOptional()
}

type User_Nickname struct {
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3,oneof"`
}

func (*User_Nickname) isUser_NicknameOptional() {}

func (m *User) GetNicknameOptional() isUser_NicknameOptional {
	if m != nil {
		return m.NicknameOptional
	}
	return nil
}

func (m *User) GetNickname() string {
	if x, ok := m.GetNicknameOptional().(*User_Nickname); ok {
		return x.Nickname
	}
	return ""
}

type isUser_AgeOptional interface {
	isUser_AgeOptional()
}

type User_Age struct {
	Age int32 `protobuf:"varint,4,opt,name=age,proto3,oneof"`
}

func (*User_Age) isUser_AgeOptional() {}

func (m *User) GetAgeOptional() isUser_AgeOptional {
	if m != nil {
		return m.AgeOptional
	}
	return nil
}

func (m *User) GetAge() int32 {
	if x, ok := m.GetAgeOptional().(*User_Age); ok {
		return x.Age
	}
	return 0
}

func (m *User) GetBirth() *Birth {
	if m != nil {
		return m.Birth
	}
	return nil
}

func (m *User) GetAddresss() *Address {
	if m != nil {
		return m.Addresss
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*User) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*User_Nickname)(nil),
		(*User_Age)(nil),
	}
}

type Birth struct {
	Datetime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`
	// Types that are valid to be assigned to WeightOptional:
	//	*Birth_Weight
	WeightOptional isBirth_WeightOptional `protobuf_oneof:"weight_optional"`
	// Types that are valid to be assigned to HospitalOptional:
	//	*Birth_Hospital
	HospitalOptional     isBirth_HospitalOptional `protobuf_oneof:"hospital_optional"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Birth) Reset()         { *m = Birth{} }
func (m *Birth) String() string { return proto.CompactTextString(m) }
func (*Birth) ProtoMessage()    {}
func (*Birth) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{1}
}

func (m *Birth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Birth.Unmarshal(m, b)
}
func (m *Birth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Birth.Marshal(b, m, deterministic)
}
func (m *Birth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Birth.Merge(m, src)
}
func (m *Birth) XXX_Size() int {
	return xxx_messageInfo_Birth.Size(m)
}
func (m *Birth) XXX_DiscardUnknown() {
	xxx_messageInfo_Birth.DiscardUnknown(m)
}

var xxx_messageInfo_Birth proto.InternalMessageInfo

func (m *Birth) GetDatetime() *timestamp.Timestamp {
	if m != nil {
		return m.Datetime
	}
	return nil
}

type isBirth_WeightOptional interface {
	isBirth_WeightOptional()
}

type Birth_Weight struct {
	Weight int32 `protobuf:"varint,2,opt,name=weight,proto3,oneof"`
}

func (*Birth_Weight) isBirth_WeightOptional() {}

func (m *Birth) GetWeightOptional() isBirth_WeightOptional {
	if m != nil {
		return m.WeightOptional
	}
	return nil
}

func (m *Birth) GetWeight() int32 {
	if x, ok := m.GetWeightOptional().(*Birth_Weight); ok {
		return x.Weight
	}
	return 0
}

type isBirth_HospitalOptional interface {
	isBirth_HospitalOptional()
}

type Birth_Hospital struct {
	Hospital string `protobuf:"bytes,3,opt,name=hospital,proto3,oneof"`
}

func (*Birth_Hospital) isBirth_HospitalOptional() {}

func (m *Birth) GetHospitalOptional() isBirth_HospitalOptional {
	if m != nil {
		return m.HospitalOptional
	}
	return nil
}

func (m *Birth) GetHospital() string {
	if x, ok := m.GetHospitalOptional().(*Birth_Hospital); ok {
		return x.Hospital
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Birth) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Birth_Weight)(nil),
		(*Birth_Hospital)(nil),
	}
}

type Address struct {
	Country Country `protobuf:"varint,1,opt,name=country,proto3,enum=entity.Country" json:"country,omitempty"`
	// Types that are valid to be assigned to ZipCodeOptional:
	//	*Address_ZipCode
	ZipCodeOptional isAddress_ZipCodeOptional `protobuf_oneof:"zipCode_optional"`
	// Types that are valid to be assigned to StateOptional:
	//	*Address_State
	StateOptional isAddress_StateOptional `protobuf_oneof:"state_optional"`
	// Types that are valid to be assigned to CityOptional:
	//	*Address_City
	CityOptional         isAddress_CityOptional `protobuf_oneof:"city_optional"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{2}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetCountry() Country {
	if m != nil {
		return m.Country
	}
	return Country_UNKNOWN
}

type isAddress_ZipCodeOptional interface {
	isAddress_ZipCodeOptional()
}

type Address_ZipCode struct {
	ZipCode int32 `protobuf:"varint,2,opt,name=zipCode,proto3,oneof"`
}

func (*Address_ZipCode) isAddress_ZipCodeOptional() {}

func (m *Address) GetZipCodeOptional() isAddress_ZipCodeOptional {
	if m != nil {
		return m.ZipCodeOptional
	}
	return nil
}

func (m *Address) GetZipCode() int32 {
	if x, ok := m.GetZipCodeOptional().(*Address_ZipCode); ok {
		return x.ZipCode
	}
	return 0
}

type isAddress_StateOptional interface {
	isAddress_StateOptional()
}

type Address_State struct {
	State string `protobuf:"bytes,3,opt,name=state,proto3,oneof"`
}

func (*Address_State) isAddress_StateOptional() {}

func (m *Address) GetStateOptional() isAddress_StateOptional {
	if m != nil {
		return m.StateOptional
	}
	return nil
}

func (m *Address) GetState() string {
	if x, ok := m.GetStateOptional().(*Address_State); ok {
		return x.State
	}
	return ""
}

type isAddress_CityOptional interface {
	isAddress_CityOptional()
}

type Address_City struct {
	City string `protobuf:"bytes,4,opt,name=city,proto3,oneof"`
}

func (*Address_City) isAddress_CityOptional() {}

func (m *Address) GetCityOptional() isAddress_CityOptional {
	if m != nil {
		return m.CityOptional
	}
	return nil
}

func (m *Address) GetCity() string {
	if x, ok := m.GetCityOptional().(*Address_City); ok {
		return x.City
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Address) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Address_ZipCode)(nil),
		(*Address_State)(nil),
		(*Address_City)(nil),
	}
}

func init() {
	proto.RegisterEnum("entity.Country", Country_name, Country_value)
	proto.RegisterType((*User)(nil), "entity.User")
	proto.RegisterType((*Birth)(nil), "entity.Birth")
	proto.RegisterType((*Address)(nil), "entity.Address")
}

func init() {
	proto.RegisterFile("proto/user.proto", fileDescriptor_d570e3e37e5899c5)
}

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x91, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x3b, 0xd9, 0x26, 0xe9, 0x9e, 0xba, 0x69, 0x7a, 0x56, 0x24, 0x14, 0xc1, 0xb2, 0x82,
	0x54, 0x85, 0x14, 0x56, 0xf0, 0xde, 0xec, 0x4d, 0x50, 0xa8, 0x32, 0x5a, 0xbc, 0x94, 0x69, 0x33,
	0xa6, 0x83, 0x6d, 0x26, 0x64, 0xa6, 0x48, 0x7d, 0x19, 0x9f, 0xc2, 0x27, 0xf1, 0x85, 0x96, 0x99,
	0xc9, 0x9f, 0xab, 0xce, 0xf7, 0x3b, 0xdf, 0x74, 0xbe, 0xf3, 0x05, 0xe2, 0xba, 0x91, 0x5a, 0xae,
	0xcf, 0x8a, 0x37, 0xa9, 0x3d, 0x62, 0xc0, 0x2b, 0x2d, 0xf4, 0x65, 0xf1, 0xa2, 0x94, 0xb2, 0x3c,
	0xf2, 0xb5, 0xa5, 0xbb, 0xf3, 0xcf, 0xb5, 0x16, 0x27, 0xae, 0x34, 0x3b, 0xd5, 0xce, 0x78, 0xf7,
	0x9f, 0xc0, 0x78, 0xab, 0x78, 0x83, 0x11, 0x78, 0xa2, 0x48, 0xc8, 0x92, 0xac, 0x7c, 0xea, 0x89,
	0x02, 0x11, 0xc6, 0x15, 0x3b, 0xf1, 0xc4, 0x5b, 0x92, 0xd5, 0x35, 0xb5, 0x67, 0x7c, 0x0e, 0x93,
	0x4a, 0xec, 0x7f, 0x59, 0x7e, 0x65, 0x78, 0x3e, 0xa2, 0x3d, 0x41, 0x84, 0x2b, 0x56, 0xf2, 0x64,
	0x6c, 0xfe, 0x22, 0x27, 0xd4, 0x08, 0x7c, 0x09, 0xfe, 0x4e, 0x34, 0xfa, 0x90, 0xf8, 0x4b, 0xb2,
	0x9a, 0xde, 0xdf, 0xa4, 0x2e, 0x57, 0x9a, 0x19, 0x48, 0xdd, 0x0c, 0xdf, 0xc2, 0x84, 0x15, 0x45,
	0xc3, 0x95, 0x52, 0x49, 0x60, 0x7d, 0xb3, 0xce, 0xf7, 0xc1, 0x71, 0xda, 0x1b, 0xb2, 0x5b, 0x98,
	0x77, 0x2f, 0xfe, 0x90, 0xb5, 0x16, 0xb2, 0x62, 0xc7, 0x2c, 0x82, 0x27, 0xac, 0x1c, 0xf4, 0xdd,
	0x5f, 0x02, 0xbe, 0x7d, 0x02, 0xdf, 0xc3, 0xa4, 0x60, 0x9a, 0x9b, 0xb5, 0xed, 0x72, 0xd3, 0xfb,
	0x45, 0xea, 0x3a, 0x49, 0xbb, 0x4e, 0xd2, 0x6f, 0x5d, 0x27, 0xb4, 0xf7, 0x62, 0x02, 0xc1, 0x6f,
	0x2e, 0xca, 0x83, 0xb6, 0x05, 0xf8, 0xf9, 0x88, 0xb6, 0xda, 0x94, 0x70, 0x90, 0xaa, 0x16, 0x9a,
	0x1d, 0xdb, 0x12, 0x08, 0xed, 0x49, 0x36, 0x87, 0x99, 0xf3, 0x0d, 0xe1, 0x6e, 0x61, 0xde, 0x8d,
	0x87, 0x84, 0xff, 0x08, 0x84, 0xed, 0x72, 0xf8, 0x1a, 0xc2, 0xbd, 0x3c, 0x57, 0xba, 0xb9, 0xd8,
	0x88, 0xd1, 0xb0, 0xfe, 0x83, 0xc3, 0xb4, 0x9b, 0xe3, 0x02, 0xc2, 0x3f, 0xa2, 0x7e, 0x90, 0x05,
	0xef, 0x73, 0x75, 0x00, 0x9f, 0x81, 0xaf, 0x34, 0xd3, 0xbc, 0x4f, 0xe5, 0x24, 0x3e, 0x85, 0xf1,
	0x5e, 0xe8, 0x8b, 0xfd, 0x30, 0xd7, 0xb9, 0x47, 0xad, 0xca, 0x10, 0xe2, 0xf6, 0xe2, 0x90, 0x34,
	0x86, 0xc8, 0x5e, 0x19, 0xc8, 0x0c, 0x6e, 0x8c, 0xbb, 0x07, 0x6f, 0x5e, 0x41, 0xd8, 0x86, 0xc2,
	0x29, 0x84, 0xdb, 0xcd, 0xa7, 0xcd, 0xe7, 0xef, 0x9b, 0x78, 0x84, 0x01, 0x78, 0xdb, 0xaf, 0x31,
	0x31, 0xbf, 0x1f, 0xbf, 0xc4, 0xde, 0x2e, 0xb0, 0xed, 0xbe, 0x7b, 0x0c, 0x00, 0x00, 0xff, 0xff,
	0x4e, 0x65, 0x80, 0xff, 0x9b, 0x02, 0x00, 0x00,
}
